services:
  Qwen3-Embedding-0.6B:
    container_name: Qwen3-Embedding-0.6B
    restart: no
    image:  vllm/vllm-openai:v0.19.0
    ipc: host
    volumes:
      - /disk1/models/Qwen/Qwen3-Embedding-0.6B/Qwen3-Embedding-0.6B:/models/qwen3-embedding-0.6b
        
    command: ["--model", "/models/qwen3-embedding-0.6b", "--served-model-name", "Qwen3-Embedding-0.6B",  "--gpu-memory-utilization", "0.08", "--max_model_len", "2048"]
    ports:
      - 8007:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
