name: mem0-dev

services:
  mem0:
    build:
      context: ..  # Set context to parent directory
      dockerfile: server/dev.Dockerfile
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./history:/app/history      # History db location
      - .:/app                      # Server code (auto-reload)
      - ../mem0:/app/packages/mem0  # Mem0 library (auto-reload)
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8888 --reload
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - LLM_BASE_URL=http://localhost:8000/v1
      - EMBEDDER_BASE_URL=http://localhost:8007/v1

  postgres:
      image: ankane/pgvector:v0.5.1
      restart: on-failure
      shm_size: "128mb"
      network_mode: host
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      healthcheck:
        test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
      volumes:
        - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
